name: Ubuntu (clang)

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_call:
    workflow_dispatch:

jobs:
    ubuntu_clang:

        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install newer Clang
              run: |
                wget https://apt.llvm.org/llvm.sh
                chmod +x ./llvm.sh
                sudo ./llvm.sh 17 all

            - name: Test Scan Dependency
              run: |
                clang-scan-deps-17 -format=p1689 -- clang++-17 -c -std=c++20 -MD -MF demo.cc.d demo.cc -o demo.o
                clang-scan-deps-17 -format=p1689 -- clang++-17 -c -std=c++20 -MD -MF foo.cppm.d foo.cppm -o foo.o

            - name: Build C++20 Modules
              run: |
                clang++-17 -c -std=c++20 foo.cppm -fmodule-output=foo.pcm -o foo.o
                clang++-17 -c -std=c++20 demo.cc -fmodule-file=foo=foo.pcm -o demo.o
                clang++-17 demo.o foo.o -o demo

            - name: Run demo
              run: ./demo