name: Ubuntu (gcc)

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_call:
    workflow_dispatch:

jobs:
    ubuntu_gcc:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              run: |
                sudo apt-get update
                sudo apt-get  install software-properties-common
                sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
                sudo apt-get  update
                sudo apt-get  install gcc-14 g++-14
            - name: Test Scan Dependency
              working-directory:
              run: |
                g++-14 -std=c++20 -E -fmodules-ts -MD -MF demo.cc.d -fdeps-file=/dev/stdout -fdeps-format=p1689r5 -fdeps-target=demo.o demo.cc -o demo.cc.pp
                g++-14 -std=c++20 -E -fmodules-ts -MD -MF foo.cppm.d -fdeps-file=/dev/stdout -fdeps-format=p1689r5 -fdeps-target=foo.o foo.cppm -o foo.cppm.pp

            - name: Build C++20 Modules foo
              run: |
                g++-14 -std=c++20 -c -fmodules-ts -MD -MF foo.cppm.d foo.cppm -fmodule-mapper=gcc.modmap -o foo.o

            - name: Check
              run: |
                ls

            - name: use C++20 Modules foo
              run: |
                g++-14 -std=c++20 -c -fmodules-ts -MD -MF demo.cc.d demo.cc -fmodule-mapper=gcc.modmap -o demo.o

            - name: Check
              run: |
                ls
                
            - name: Link
              run: |
                g++-14 foo.o demo.o -o demo

            - name: Run demo
              run: ./demo