name: Windows MSVC

on:
    workflow_call:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    windows_msvc:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Enable Developer Command Prompt
              uses: ilammy/msvc-dev-cmd@v1.12.0
            - name: Test Scan Dependency
              run: |
                cl /std:c++latest /scanDependencies- demo.cc /Fodemo.obj
                cl /std:c++latest /scanDependencies- /TP foo.cppm /ifcOutput foo.pcm /Fofoo.obj
            - name: Build C++20 Modules
              run: |
                cl /c /std:c++latest /interface /TP foo.cppm /ifcOutput foo.pcm /Fofoo.obj
                cl /c /std:c++latest demo.cc /reference foo=foo.pcm /Fodemo.obj
                cl /std:c++latest demo.obj foo.obj /Fedemo
                dir

            - name: Run demo
              run: ./demo.exe
 